INSERT INTO Person(ID, FIRST_NAME, LAST_NAME, BIRTHDATE) VALUES (1, 'John', 'Doe', '1970-01-01');
INSERT INTO Person(ID, FIRST_NAME, LAST_NAME, BIRTHDATE) VALUES (2, 'Jane', 'Doe', '1970-01-01');
INSERT INTO Person(ID, FIRST_NAME, LAST_NAME)            VALUES (3, 'Brian', 'Goetz');
